name: tensorflow-py3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy=1.19
  - pandas=1.1
  - matplotlib=3.1
  - seaborn=0.10
  - scikit-learn=0.21.3
  - scipy=1.3
  - statsmodels=0.11
  - jupyter
  - ipykernel
  - notebook
  - qt
  - pyqt
  - libblas
  - liblapack
  - openblas
  - pip:
      - tensorflow==2.7.0
      - tensorflow-estimator==2.7.0
      - tensorboard==2.7.0
      - tensorflow-probability==0.11.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.1
      - absl-py==0.7.1
      - grpcio==1.24.3
      - h5py==2.9.0
      - markdown==3.1.1
      - protobuf==3.9.2
      - six==1.12.0
      - termcolor==1.1.0
      - wrapt==1.11.2
